// Generated from the MDX frontmatter by scripts/generate-content.mjs.
import type { BlogFrontmatter } from "../schema";

export const blogMetadata: readonly ({ slug: string } & BlogFrontmatter)[] = [
  {
    slug: "agent-task-half-life",
    title: "Your agent has a half-life",
    description:
      "Why AI agents keep failing on long multi-step jobs: a 95% reliable agent finishes 48 steps 8.5% of the time. The fix is a resumable run, not a better model.",
    published: "2026-08-11",
    seoTitle: "Why AI Agents Keep Failing on Long Multi-Step Tasks",
    author: "ankush",
    tags: ["ai-agent", "reliability", "workflow-automation", "product"],
    kind: "article",
    draft: false,
  },
  {
    slug: "agent-verification-gap",
    title: "Nobody merges an email",
    description:
      "Agents made work cheap to produce and no cheaper to check. Why software absorbed the flood, why the rest of the business did not, and the five things that make agent work checkable.",
    published: "2026-09-22",
    seoTitle: "Why AI Agent Work Is Hard to Verify Outside Code",
    author: "ankush",
    tags: ["ai-agent", "reliability", "product", "ai-employee"],
    kind: "article",
    draft: false,
  },
  {
    slug: "ai-agent-email-address",
    title: "How to Give an AI Agent Its Own Email Address",
    description:
      "Three ways to give an AI agent its own inbox: a product with a native agent address, a developer email API, or delegated Gmail access. Trade-offs and steps.",
    published: "2026-10-14",
    seoTitle: "How to Give an AI Agent Its Own Email Address (2026)",
    author: "nischal",
    tags: ["ai-agent", "email", "ai-employee"],
    kind: "guide",
    draft: false,
  },
  {
    slug: "ai-agent-memory",
    title: "AI Agent Memory You Can Control",
    description:
      "Give an AI agent persistent memory with provenance, corrections, temporal context, and controls to inspect, update, forget, or restore what it knows.",
    published: "2026-07-20",
    updated: "2026-07-27",
    author: "nischal",
    tags: ["ai-agent-memory", "persistent-memory", "ai-agent"],
    kind: "guide",
    draft: false,
  },
  {
    slug: "ai-agent-vs-virtual-assistant",
    title: "AI Agent vs Virtual Assistant: Cost and Capabilities",
    description:
      "AI agent vs virtual assistant: compare monthly cost, availability, and inspectable work records before you replace suitable VA tasks with a supervised AI employee.",
    published: "2026-07-25",
    updated: "2026-09-22",
    seoTitle: "AI Agent vs Virtual Assistant: Cost Comparison",
    author: "ankush",
    tags: ["ai-agent", "virtual-assistant", "pricing", "comparison"],
    kind: "article",
    draft: false,
  },
  {
    slug: "ai-agent-vs-zapier",
    title: "AI Agent vs Zapier Automation",
    description:
      "Zapier runs a fixed trigger-action recipe. See how an AI agent plans its own steps instead, with a side-by-side of the same recurring workflow built both ways.",
    published: "2026-07-26",
    updated: "2026-07-27",
    author: "ankush",
    tags: ["comparison", "zapier", "ai-agent", "automation"],
    kind: "article",
    draft: false,
  },
  {
    slug: "ai-agent-with-its-own-computer",
    title: "What is an AI agent with its own computer?",
    description:
      "An AI agent with its own computer keeps working in a cloud workspace after you close your laptop. How it works, the risks, and who offers one, from $9 a month.",
    published: "2026-10-07",
    seoTitle:
      "AI Agent With Its Own Computer: What It Is and Who Offers One (2026)",
    author: "ankush",
    tags: ["ai-agent", "always-on-agent", "ai-employee", "product"],
    kind: "article",
    draft: false,
  },
  {
    slug: "ai-employee",
    title: "AI Employee for Real Business Work",
    description:
      "Meet the AI employee that researches, operates tools, creates files, and runs recurring work from a persistent, supervised workspace.",
    published: "2026-07-20",
    updated: "2026-09-22",
    author: "nischal",
    tags: ["ai-employee", "ai-agent", "business-automation"],
    kind: "guide",
    draft: false,
  },
  {
    slug: "ai-workflow-automation",
    title: "AI Workflow Automation",
    description:
      "Create reusable linear AI workflows, run them on demand, or schedule recurring work across files, live browser runs, native email, and connected business apps.",
    published: "2026-07-20",
    updated: "2026-07-27",
    author: "nischal",
    tags: ["workflow-automation", "ai-agent", "scheduling"],
    kind: "guide",
    draft: false,
  },
  {
    slug: "best-ai-employee-platforms",
    title: "AI employees for small business: 10 platforms compared",
    description:
      "The best AI employee platforms for small business in 2026, compared on price, capabilities, and limits: Lindy, Sintra, Marblism, Manus, Construct, and more.",
    published: "2026-09-29",
    seoTitle: "Best AI Employees for Small Business (2026): 10 Compared",
    author: "construct-team",
    tags: ["comparison", "ai-employee", "small-business"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "build-internal-tools-with-construct",
    title: "How Construct Builds Internal Tools in Your Workspace",
    description:
      "Turn a repeated process into a private workspace app that Construct can build, validate, debug, and update while preserving the last successful build.",
    published: "2026-07-27",
    author: "ankush",
    tags: ["internal-tools", "workspace-apps", "ai-agent", "product"],
    kind: "article",
    draft: false,
  },
  {
    slug: "chat-assistants-vs-ai-employees",
    title: "Chat Assistants vs AI Employees",
    description:
      "ChatGPT and Claude are great at drafting, but autonomous ops need execution, persistence, and inspectable work. See how Construct compares to chat assistants.",
    published: "2026-06-15",
    updated: "2026-07-27",
    author: "ankush",
    tags: ["comparison", "chatgpt", "ai-employee"],
    kind: "article",
    draft: false,
  },
  {
    slug: "chatgpt-dots-alternatives",
    title:
      "ChatGPT Dots alternatives: 9 always-on agents that don't need ChatGPT Pro",
    description:
      "ChatGPT Dots needs a Pro or Business Premium plan. Compare 9 always-on agent alternatives from $0 to $50 a month, and which subscription each one needs.",
    published: "2026-10-04",
    seoTitle: "ChatGPT Dots Alternatives: 9 Agents Without ChatGPT Pro (2026)",
    author: "construct-team",
    tags: ["comparison", "chatgpt", "ai-employee", "ai-agent"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "construct-vs-chatgpt",
    title: "Construct vs ChatGPT, Claude, and Gemini",
    description:
      "Compare Construct with chat assistants such as ChatGPT, Claude, and Gemini across workspace, tools, memory, schedules, and workflows.",
    published: "2026-07-20",
    updated: "2026-07-27",
    author: "construct-team",
    tags: ["comparison", "chat-assistants", "chatgpt", "ai-employee"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "construct-vs-coding-agents",
    title: "Construct vs coding-focused agents",
    description:
      "Compare Construct with coding agents. See when a generalist AI employee for email, research, calendar, CRM, and code is the better fit.",
    published: "2026-07-20",
    updated: "2026-07-27",
    author: "construct-team",
    tags: ["comparison", "coding-agents", "ai-employee"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "construct-vs-copilot",
    title: "Construct vs Microsoft Copilot and Google Workspace AI",
    description:
      "Compare Construct with Microsoft Copilot and Google Workspace AI. See how one vendor-neutral AI employee works across apps from a persistent workspace.",
    published: "2026-07-20",
    updated: "2026-07-27",
    author: "construct-team",
    tags: ["comparison", "copilot", "google-workspace", "ai-employee"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "construct-vs-diy",
    title: "Construct vs building your own AI agent",
    description:
      "Building your own agent means wiring sandbox, apps, channels, memory, schedules, and user-facing activity summaries yourself. Construct provides those pieces as a hosted product.",
    published: "2026-07-20",
    updated: "2026-09-29",
    seoTitle: "Turnkey AI System vs Building Your Own AI Agent",
    author: "construct-team",
    tags: ["comparison", "agent-frameworks", "diy", "ai-employee"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "construct-vs-lindy",
    title: "Construct vs Lindy",
    description:
      "Construct vs Lindy on pricing, where each works, memory, activity records, and model keys. Lindy starts at $29.99 per user; Construct starts at $9.",
    published: "2026-10-12",
    seoTitle: "Lindy Alternative: Construct vs Lindy (2026)",
    author: "construct-team",
    tags: ["comparison", "ai-employee", "small-business"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "construct-vs-openai-dots",
    title: "Construct vs ChatGPT Dots",
    description:
      "Compare Construct and ChatGPT Dots on price, model choice, approvals, memory, apps, and channels. Dots needs ChatGPT Pro; Construct starts at $9/month.",
    published: "2026-10-01",
    seoTitle: "ChatGPT Dots Alternative: Construct vs Dots",
    author: "construct-team",
    tags: ["comparison", "chatgpt", "ai-employee"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "construct-vs-zapier",
    title: "Construct vs Zapier, Make, and n8n",
    description:
      "Compare Construct with Zapier, Make, and n8n for deterministic workflows, agentic steps, scheduling, and ambiguous multi-step work.",
    published: "2026-07-20",
    updated: "2026-07-27",
    author: "construct-team",
    tags: ["comparison", "zapier", "make", "n8n", "workflow-automation"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "gemini-spark-alternatives",
    title:
      "Gemini Spark alternatives, including for Workspace accounts and the UK and EU",
    description:
      "Gemini Spark needs a personal Google account and skips the UK and EU. Compare 7 always-on agents on price, work accounts, and regional availability.",
    published: "2026-10-17",
    seoTitle: "Gemini Spark Alternatives (2026): Options for Work Accounts",
    author: "construct-team",
    tags: ["comparison", "gemini-spark", "google-workspace", "ai-employee"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "grokbot-alternative",
    title: "Grok Bot Alternative: Construct vs Grok Bot",
    description:
      "Compare Construct and Grok Bot on monthly pricing, workflows, integrations, memory, and model choice for small teams.",
    published: "2026-09-10",
    updated: "2026-09-22",
    seoTitle: "Grok Bot Alternative: Construct vs Grok Bot",
    author: "construct-team",
    tags: ["comparison", "ai-employee", "workflow-automation"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "how-to-choose-an-ai-agent-platform-for-your-team",
    title: "How to Choose an AI Agent Platform for Your Team",
    description:
      "A vendor-agnostic evaluation checklist for AI agent platforms: pilot-failure data, six evaluation criteria, governance pressure, and a scorecard you can reuse.",
    published: "2026-07-28",
    author: "nischal",
    tags: ["ai-agent", "ai-employee", "governance", "product"],
    kind: "guide",
    draft: false,
  },
  {
    slug: "jev-ai-agents",
    title: "We put Jev inside our AI employee",
    description:
      "We shipped TypeSafe's Jev into our AI employee's memory five days after launch: measured latency, how we set a 0.7 threshold, where Jev fails, and what it costs.",
    published: "2026-09-30",
    seoTitle: "Jev for AI Agents: What We Learned Running It in Production",
    author: "ankush",
    tags: ["ai-agent", "jev", "reliability", "decision-models"],
    kind: "article",
    draft: false,
  },
  {
    slug: "muse-for-small-business-alternatives",
    title: "Muse for Small Business alternatives: 9 AI agents for work",
    description:
      "Meta's Muse for Small Business is free to start. Here are 9 alternatives for running a business, with prices checked October 1, 2026, and where each fits.",
    published: "2026-10-09",
    seoTitle: "Meta Muse for Small Business Alternatives (2026)",
    author: "construct-team",
    tags: ["comparison", "ai-employee", "small-business"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "running-ai-agents-on-cloudflare-not-vms",
    title: "All our Agents get computers, we pay for almost none",
    description:
      "Construct is an AI employee with a real Linux computer per user. Don't get excited - we are not paying for all of them. How we run that on Cloudflare Durable Objects, Sandboxes, and R2.",
    published: "2026-07-31",
    seoTitle: "Running AI Agents on Cloudflare Without Always-On VMs",
    author: "ankush",
    tags: ["engineering", "cloudflare", "durable-objects", "infrastructure"],
    kind: "article",
    draft: false,
  },
  {
    slug: "what-is-an-ai-employee",
    title: "What is an AI employee?",
    description:
      "Learn what an AI employee is, how it differs from a chatbot, and how Construct completes work across email, Slack, browser, and connected apps.",
    published: "2026-07-02",
    updated: "2026-09-29",
    seoTitle: "What Is an AI Employee? Definition and Examples",
    author: "ankush",
    tags: ["ai-agent", "product", "ai-employee"],
    kind: "article",
    draft: false,
  },
  {
    slug: "zen-mode",
    title: "Zen Mode: some days you just want it done",
    description:
      "Zen Mode is a chat-first way into Construct's AI computer. Ask once, it works in the background, asks when it needs you, and runs on your phone.",
    published: "2026-09-30",
    seoTitle: "Construct Zen Mode: Chat-First AI Agent With Its Own Computer",
    author: "nischal",
    tags: ["product", "ai-agent", "ai-employee", "zen-mode"],
    kind: "guide",
    draft: true,
  },
];
