// Generated from the MDX frontmatter by scripts/generate-content.mjs.
import type { BlogFrontmatter } from "../schema";

export const blogMetadata: readonly ({ slug: string } & BlogFrontmatter)[] = [
  {
    slug: "agent-reliability-calculator",
    title:
      "Agent reliability calculator: how many steps will your agent finish?",
    description:
      "Enter per-step success and step count to see how often an AI agent finishes in one run, how many retries it needs, and what checkpoints change.",
    published: "2026-10-14",
    seoTitle: "Agent Reliability Calculator: Why AI Agents Fail on Long Tasks",
    author: "ankush",
    tags: ["ai-agent", "reliability", "workflow-automation", "engineering"],
    kind: "article",
    draft: true,
  },
  {
    slug: "agent-task-half-life",
    title: "Your agent has a half-life",
    description:
      "Why AI agents keep failing on long multi-step jobs: a 95% reliable agent finishes 48 steps 8.5% of the time. The fix is a resumable run, not a better model.",
    published: "2026-08-11",
    seoTitle: "Why AI Agents Keep Failing on Long Multi-Step Tasks",
    author: "ankush",
    tags: ["ai-agent", "reliability", "workflow-automation", "product"],
    kind: "article",
    draft: false,
  },
  {
    slug: "agent-verification-gap",
    title: "Nobody merges an email",
    description:
      "Agents made work cheap to produce and no cheaper to check. Why software absorbed the flood, why the rest of the business did not, and the five things that make agent work checkable.",
    published: "2026-09-22",
    seoTitle: "Why AI Agent Work Is Hard to Verify Outside Code",
    author: "ankush",
    tags: ["ai-agent", "reliability", "product", "ai-employee"],
    kind: "article",
    draft: false,
  },
  {
    slug: "ai-agent-activity-log",
    title:
      "Activity log vs audit log: what an AI agent should record for a small team",
    description:
      "An activity log tells you what your AI agent did and why. An audit log proves it. What Construct's Activity records, keeps for 30 days, and leaves out.",
    published: "2026-10-22",
    seoTitle:
      "AI Agent Activity Log vs Audit Log: What It Should Record (2026)",
    author: "nischal",
    tags: ["ai-agent", "governance", "product"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-agent-browser-and-terminal",
    title: "Browser and terminal in one supervised task",
    description:
      "How Construct's agent uses a live cloud browser and a Linux terminal in one job, what you can watch and stop, and the five-minute limits to plan around.",
    published: "2026-10-29",
    seoTitle:
      "An AI Agent That Uses a Browser and a Terminal in One Task (2026)",
    author: "nischal",
    tags: ["ai-agent", "product", "workflow-automation"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-agent-custom-mcp",
    title: "Connect your own tools: custom MCP and permission boundaries",
    description:
      "Add your own MCP server to Construct by URL, and set which agents can use it. Requirements, the 15-second call limit, permission boundaries, and gaps.",
    published: "2026-11-16",
    seoTitle: "AI Agent Custom MCP Tools: How to Connect Them Safely (2027)",
    author: "nischal",
    tags: ["ai-agent", "product", "governance"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-agent-email-address",
    title: "How to Give an AI Agent Its Own Email Address",
    description:
      "Three ways to give an AI agent its own inbox: a product with a native agent address, a developer email API, or delegated Gmail access. Trade-offs and steps.",
    published: "2026-10-08",
    seoTitle: "How to Give an AI Agent Its Own Email Address (2026)",
    author: "nischal",
    tags: ["ai-agent", "email", "ai-employee"],
    kind: "guide",
    draft: false,
  },
  {
    slug: "ai-agent-files-and-artifacts",
    title:
      "Where your agent's work goes: files, reports and apps that outlast the chat",
    description:
      "Construct saves agent work as files, PDFs, spreadsheets and small apps in a workspace with 100 MB to 3 GB of storage. How it works, and its limits.",
    published: "2026-11-07",
    seoTitle:
      "AI Agent Persistent Files: Reports and Apps That Outlast the Chat",
    author: "nischal",
    tags: ["ai-agent", "product", "internal-tools"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-agent-gmail-access-safely",
    title: "How to Let an AI Agent Use Your Gmail Safely",
    description:
      "Let an AI agent work with your Gmail without risking your inbox: scopes, drafts before sends, a separate agent inbox, reviewing activity, and revoking access.",
    published: "2026-10-11",
    seoTitle: "How to Safely Give an AI Agent Gmail Access (2026)",
    author: "nischal",
    tags: ["email", "ai-agent", "google-workspace", "governance"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-agent-linear-from-slack",
    title: "Update Linear Issues From Slack Messages With an AI Agent",
    description:
      "Mention an AI agent in Slack to create, update, and comment on Linear issues, including several at once. Setup, exact prompts, limits, and fixes, from $9.",
    published: "2026-11-03",
    seoTitle: "Update Linear Issues From Slack With an AI Agent (2026 Guide)",
    author: "nischal",
    tags: ["ai-agent", "workflow-automation", "small-business"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-agent-memory",
    title: "AI Agent Memory You Can Control",
    description:
      "Give an AI agent persistent memory with provenance, corrections, temporal context, and controls to inspect, update, forget, or restore what it knows.",
    published: "2026-07-20",
    updated: "2026-10-01",
    author: "nischal",
    tags: ["ai-agent-memory", "persistent-memory", "ai-agent"],
    kind: "guide",
    draft: false,
  },
  {
    slug: "ai-agent-prompt-injection",
    title:
      "Prompt injection for small teams: when your agent reads a hostile email",
    description:
      "Any agent that reads email can be steered by a stranger's message. What prompt injection is, the lethal trifecta, practical controls, and where Construct stands.",
    published: "2026-11-12",
    seoTitle: "Prompt Injection and AI Email Agents: A Small Team's Guide",
    author: "ankush",
    tags: ["ai-agent", "email", "governance", "reliability"],
    kind: "article",
    draft: true,
  },
  {
    slug: "ai-agent-scheduled-tasks",
    title: "How to Run an AI Agent on a Schedule With Your Laptop Closed",
    description:
      "Schedule an AI agent job that runs in the cloud while your laptop is shut. Plans include 3, 10, or 50 scheduled tasks. Steps, exact prompts, and limits.",
    published: "2026-10-19",
    seoTitle: "How to Run an AI Agent on a Schedule (Laptop Closed, 2026)",
    author: "nischal",
    tags: ["scheduling", "ai-agent", "workflow-automation"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-agent-slack-briefing",
    title: "A Morning Slack Briefing From Your AI Agent",
    description:
      "Have an AI agent prepare a weekday briefing at 7:45am and get it into Slack, from $9 a month. Exact prompts, setup steps, limits, and fixes.",
    published: "2026-10-26",
    seoTitle: "AI Agent Morning Slack Briefing: Setup Guide (2026)",
    author: "nischal",
    tags: ["ai-agent", "scheduling", "email"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-agent-telegram-slack-discord",
    title:
      "How to Message Your AI Agent From Telegram, Slack, Discord or Email",
    description:
      "Connect one AI agent to Slack, Telegram, Discord and email, then set who can use it in each place. Setup steps, exact prompts, and access rules.",
    published: "2026-11-08",
    seoTitle: "Message Your AI Agent From Telegram, Slack, Discord or Email",
    author: "nischal",
    tags: ["ai-agent", "ai-employee", "email"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-agent-vs-virtual-assistant",
    title: "AI Agent vs Virtual Assistant: Cost and Capabilities",
    description:
      "AI agent vs virtual assistant: compare monthly cost, availability, and inspectable work records before you replace suitable VA tasks with a supervised AI employee.",
    published: "2026-07-25",
    updated: "2026-10-01",
    seoTitle: "AI Agent vs Virtual Assistant: Cost Comparison",
    author: "ankush",
    tags: ["ai-agent", "virtual-assistant", "pricing", "comparison"],
    kind: "article",
    draft: false,
  },
  {
    slug: "ai-agent-vs-zapier",
    title: "AI Agent vs Zapier Automation",
    description:
      "Zapier runs a fixed trigger-action recipe. See how an AI agent plans its own steps instead, with a side-by-side of the same recurring workflow built both ways.",
    published: "2026-07-26",
    updated: "2026-10-01",
    author: "ankush",
    tags: ["comparison", "zapier", "ai-agent", "automation"],
    kind: "article",
    draft: false,
  },
  {
    slug: "ai-agent-with-its-own-computer",
    title: "What is an AI agent with its own computer?",
    description:
      "An AI agent with its own computer keeps working in a cloud workspace after you close your laptop. How it works, the risks, and who offers one, from $9 a month.",
    published: "2026-10-05",
    seoTitle:
      "AI Agent With Its Own Computer: What It Is and Who Offers One (2026)",
    author: "ankush",
    tags: ["ai-agent", "always-on-agent", "ai-employee", "product"],
    kind: "article",
    draft: false,
  },
  {
    slug: "ai-company-research-spreadsheet",
    title:
      "How to Research a List of Companies Into a Spreadsheet, With Sources",
    description:
      "Give an AI agent a list of companies and get back a spreadsheet with one row each and a source link for every fact. Exact prompts, checks, and limits.",
    published: "2026-10-23",
    seoTitle:
      "AI Company Research Into a Spreadsheet, With Sources (Step by Step)",
    author: "nischal",
    tags: ["ai-agent", "small-business", "workflow-automation"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-competitor-pricing-report",
    title: "How to Build a Weekly Competitor Pricing Report With an AI Agent",
    description:
      "Have an AI agent check competitor pricing pages every week, save a dated snapshot, compare it with last week's, and post what changed. Prompts and limits.",
    published: "2026-11-11",
    seoTitle: "Weekly Competitor Pricing Report With AI: Step-by-Step Setup",
    author: "nischal",
    tags: ["ai-agent", "workflow-automation", "scheduling", "pricing"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-coworker-vs-ai-employee",
    title: "AI coworker, AI employee or AI assistant: which one you need",
    description:
      "An AI assistant answers when you ask, an AI coworker works beside you, and an AI employee owns a recurring job. A decision guide, with prices from $9 to $50 a month.",
    published: "2026-11-20",
    seoTitle: "AI Coworker vs AI Employee vs AI Assistant: Which Do You Need?",
    author: "ankush",
    tags: ["ai-employee", "ai-agent", "chatgpt", "small-business"],
    kind: "article",
    draft: true,
  },
  {
    slug: "ai-delegation-checklist",
    title: "The AI delegation checklist",
    description:
      "A one-page checklist for delegating a job to an AI agent: what to hand over, inputs, done criteria, review, and irreversible steps. Copy it and use it.",
    published: "2026-10-24",
    seoTitle:
      "AI Delegation Checklist: What to Hand an AI Agent, With a Worked Example",
    author: "nischal",
    tags: ["ai-agent", "ai-employee", "workflow-automation", "governance"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-employee",
    title: "AI Employee for Real Business Work",
    description:
      "Meet the AI employee that researches, operates tools, creates files, and runs recurring work from a persistent, supervised workspace.",
    published: "2026-07-20",
    updated: "2026-10-01",
    author: "nischal",
    tags: ["ai-employee", "ai-agent", "business-automation"],
    kind: "guide",
    draft: false,
  },
  {
    slug: "ai-employee-cost-calculator",
    title: "AI employee vs virtual assistant cost calculator",
    description:
      "Compare a virtual assistant's monthly cost with an AI agent plan plus review time. Enter VA hours, hourly rate, and the share of tasks an agent can take.",
    published: "2026-11-04",
    seoTitle: "Virtual Assistant vs AI Agent Cost Calculator",
    author: "nischal",
    tags: ["virtual-assistant", "ai-employee", "pricing", "small-business"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-employee-for-agencies",
    title: "An AI employee for a small marketing agency",
    description:
      "How a small marketing agency can hand client reports, briefs, and an approval queue to an AI employee, from $9 a month, with clients kept behind a review step.",
    published: "2026-11-02",
    seoTitle:
      "AI Employee for a Marketing Agency: Client Reports, Briefs, and Approvals",
    author: "nischal",
    tags: [
      "ai-employee",
      "small-business",
      "internal-tools",
      "workflow-automation",
    ],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-employee-for-consultants",
    title: "An AI employee for a one-person consulting business",
    description:
      "Give a solo consultancy's research, proposals, status updates, and follow-ups to an AI employee from $9 a month, with client email kept as drafts you approve.",
    published: "2026-11-27",
    seoTitle:
      "AI Tools for Consultants: An AI Employee for a One-Person Consultancy",
    author: "nischal",
    tags: ["ai-employee", "small-business", "workflow-automation", "email"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-employee-team-workspace",
    title: "One AI employee for the whole team: shared workspaces and roles",
    description:
      "How a small team shares one Construct workspace: invites, owner, admin and member roles, shared files and group chats, with no per-seat charge.",
    published: "2026-11-29",
    seoTitle:
      "An AI Coworker for a Small Team: Shared Workspaces and Roles (2027)",
    author: "nischal",
    tags: ["ai-employee", "small-business", "governance", "product"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-follow-ups-crm-without-zapier",
    title: "Customer Follow-Ups and CRM Updates Without Zapier",
    description:
      "Use Construct to find deals that need a follow-up, draft the emails, and update your CRM while you approve each send. From $9 a month, with no Zaps to build.",
    published: "2026-11-23",
    seoTitle: "Automate Follow-Up Emails and CRM Updates Without Zapier",
    author: "nischal",
    tags: ["ai-agent", "zapier", "workflow-automation", "small-business"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-inbox-triage",
    title: "Inbox Triage With an AI Agent: Drafts, Not Sends",
    description:
      "Set up an AI agent that sorts your Gmail into Reply needed, FYI, and Later, and drafts replies you send yourself. Exact prompts, from $9 a month.",
    published: "2026-10-17",
    seoTitle: "AI Inbox Triage: Let an Agent Label and Draft, Not Send (2026)",
    author: "nischal",
    tags: ["email", "ai-agent", "google-workspace"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-investor-update",
    title: "A Weekly Investor Update Drafted by Your AI Agent",
    description:
      "Have an AI agent draft your weekly investor update from GitHub, Linear and your CRM, with every claim linked. You check the numbers and send it yourself.",
    published: "2026-11-24",
    seoTitle:
      "Weekly Investor Update With AI: Drafted by an Agent, Sent by You",
    author: "nischal",
    tags: ["ai-agent", "workflow-automation", "scheduling", "small-business"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-lead-sourcing-hubspot",
    title: "New Leads Into HubSpot With a Slack Summary Every Morning",
    description:
      "Have an AI agent find new leads overnight, add them to HubSpot without duplicates, and send a summary to Slack each morning. Exact prompts and limits.",
    published: "2026-10-31",
    seoTitle:
      "AI Lead Sourcing Into HubSpot, With a Daily Slack Summary (2026)",
    author: "nischal",
    tags: ["ai-agent", "workflow-automation", "small-business", "scheduling"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "ai-search-recommends-ai-employees",
    title:
      "Which AI employees do ChatGPT, Perplexity, Gemini, Google, Claude and Grok recommend?",
    description:
      "We asked six AI engines 60 buyer questions about AI employees: which products ChatGPT, Perplexity, Gemini, Google, Claude and Grok name, and what they cite.",
    published: "2026-11-28",
    seoTitle: "Best AI Employee? What 6 AI Search Engines Recommend",
    author: "ankush",
    tags: ["ai-employee", "ai-search", "ai-agent"],
    kind: "article",
    draft: true,
  },
  {
    slug: "ai-workflow-automation",
    title: "AI Workflow Automation",
    description:
      "Create reusable linear AI workflows, run them on demand, or schedule recurring work across files, live browser runs, native email, and connected business apps.",
    published: "2026-07-20",
    updated: "2026-10-01",
    author: "nischal",
    tags: ["workflow-automation", "ai-agent", "scheduling"],
    kind: "guide",
    draft: false,
  },
  {
    slug: "always-on-ai-agents-compared",
    title: "Dots vs Muse vs Grok Bot vs Claude Cowork for a small business",
    description:
      "Four always-on AI agents compared for a small business: price per seat, accounts you need, regions, data access, and approvals. Checked October 1, 2026.",
    published: "2026-10-13",
    seoTitle: "Dots vs Muse vs Grok Bot vs Claude Cowork (2026)",
    author: "construct-team",
    tags: ["comparison", "small-business", "ai-agent"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "best-ai-employee-for-solo-founders",
    title: "Best AI employees for solo founders (2026), ranked honestly",
    description:
      "The best AI employees for a one-person company, ranked on monthly cost, setup, and how much supervision each needs. Most cost $9 to $44 a month.",
    published: "2026-10-16",
    seoTitle: "Best AI Employee for Solo Founders (2026): 8 Ranked",
    author: "construct-team",
    tags: ["comparison", "ai-employee", "small-business"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "best-ai-employee-platforms",
    title: "AI employees for small business: 10 platforms compared",
    description:
      "The best AI employee platforms for small business in 2026, ranked on price, capabilities, and limits: Construct, CellCog, Manus, Lindy, Sintra, and more.",
    published: "2026-09-29",
    updated: "2026-10-01",
    seoTitle: "Best AI Employees for Small Business (2026): 10 Compared",
    author: "construct-team",
    tags: ["comparison", "ai-employee", "small-business"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "build-internal-tools-with-construct",
    title: "How Construct Builds Internal Tools in Your Workspace",
    description:
      "Turn a repeated process into a private workspace app that Construct can build, validate, debug, and update while preserving the last successful build.",
    published: "2026-07-27",
    updated: "2026-10-01",
    author: "ankush",
    tags: ["internal-tools", "workspace-apps", "ai-agent", "product"],
    kind: "article",
    draft: false,
  },
  {
    slug: "chat-assistants-vs-ai-employees",
    title: "Chat Assistants vs AI Employees",
    description:
      "ChatGPT and Claude are great at drafting, but autonomous ops need execution, persistence, and inspectable work. See how Construct compares to chat assistants.",
    published: "2026-06-15",
    updated: "2026-10-01",
    author: "ankush",
    tags: ["comparison", "chatgpt", "ai-employee"],
    kind: "article",
    draft: false,
  },
  {
    slug: "chatgpt-dots-alternatives",
    title:
      "ChatGPT Dots alternatives: 9 always-on agents that don't need ChatGPT Pro",
    description:
      "ChatGPT Dots needs a Pro or Business Premium plan. Compare 9 always-on agent alternatives from $0 to $50 a month, and which subscription each one needs.",
    published: "2026-10-03",
    seoTitle: "ChatGPT Dots Alternatives: 9 Agents Without ChatGPT Pro (2026)",
    author: "construct-team",
    tags: ["comparison", "chatgpt", "ai-employee", "ai-agent"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "cheapest-ai-employee",
    title: "What $10 and $20 a month buys in an AI agent",
    description:
      "The cheapest AI employee we found is Construct Lite at $9. At $20 a month, Claude, Gemini, Manus, Muse and Grok Bot come bundled. What each plan buys.",
    published: "2026-11-21",
    seoTitle:
      "Cheapest AI Employee: What $10 and $20 a Month Buys in an AI Agent",
    author: "construct-team",
    tags: ["pricing", "ai-employee", "comparison", "small-business"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "claude-cowork-alternatives",
    title: "Claude Cowork alternatives after the cloud launch",
    description:
      "Claude Cowork now runs in the cloud and is part of Claude Pro at $20. Here are 10 alternatives, from $0 to $200 a month, and when each is the better fit.",
    published: "2026-10-30",
    seoTitle:
      "Claude Cowork Alternatives (2026): 10 Options After the Cloud Move",
    author: "construct-team",
    tags: ["comparison", "ai-employee", "claude-cowork"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "clef-vs-jev-benchmark",
    title: "Clef beat Jev on Jev's home turf",
    description:
      "We ran Cloudflare's Clef and Clef-flash against Jev on five production AI agent decisions: 1,053 calls, accuracy, determinism, drift, cost, and what we are switching.",
    published: "2026-10-05",
    seoTitle:
      "Clef vs Jev Benchmark: Cloudflare's Decision Model on Real Agent Prompts",
    author: "ankush",
    tags: ["ai-agent", "clef", "decision-models", "reliability", "benchmark"],
    kind: "article",
    draft: false,
    image: "clef-vs-jev-benchmark.png",
  },
  {
    slug: "construct-computer-alternatives",
    title: "Construct Computer alternatives: what you would give up",
    description:
      "Construct runs recurring team work from $9 a month. Twelve alternatives, what each costs you by comparison, and what to try before you switch.",
    published: "2026-11-25",
    seoTitle:
      "Construct Computer Alternatives: What You Give Up by Switching (2027)",
    author: "construct-team",
    tags: ["comparison", "ai-employee", "small-business"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "construct-vs-cellcog",
    title: "Construct vs CellCog",
    description:
      "Construct vs CellCog on price, shifts vs schedules, phone and meetings, memory, and model keys. CellCog starts at $8 in credits; Construct at a fixed $9.",
    published: "2026-11-22",
    seoTitle: "CellCog Alternative: Construct vs CellCog (2027)",
    author: "construct-team",
    tags: ["comparison", "ai-employee", "small-business"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "construct-vs-chatgpt",
    title: "Construct vs ChatGPT, Claude, and Gemini",
    description:
      "Compare Construct with chat assistants such as ChatGPT, Claude, and Gemini across workspace, tools, memory, schedules, and workflows.",
    published: "2026-07-20",
    updated: "2026-10-01",
    author: "construct-team",
    tags: ["comparison", "chat-assistants", "chatgpt", "ai-employee"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "construct-vs-claude-cowork",
    title: "Construct vs Claude Cowork",
    description:
      "Construct gives your team one AI employee with shared files, schedules, and your choice of model from $9 a month. Cowork starts at $20 and is personal.",
    published: "2026-10-15",
    seoTitle: "Claude Cowork Alternative: Construct vs Cowork (2026)",
    author: "construct-team",
    tags: ["comparison", "ai-employee", "claude-cowork"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "construct-vs-coding-agents",
    title: "Construct vs coding-focused agents",
    description:
      "Compare Construct with coding agents. See when a generalist AI employee for email, research, calendar, CRM, and code is the better fit.",
    published: "2026-07-20",
    updated: "2026-10-01",
    author: "construct-team",
    tags: ["comparison", "coding-agents", "ai-employee"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "construct-vs-copilot",
    title: "Construct vs Microsoft Copilot and Google Workspace AI",
    description:
      "Compare Construct with Microsoft Copilot and Google Workspace AI. See how one vendor-neutral AI employee works across apps from a persistent workspace.",
    published: "2026-07-20",
    updated: "2026-10-01",
    author: "construct-team",
    tags: ["comparison", "copilot", "google-workspace", "ai-employee"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "construct-vs-diy",
    title: "Construct vs building your own AI agent",
    description:
      "Building your own agent means wiring sandbox, apps, channels, memory, schedules, and user-facing activity summaries yourself. Construct provides those pieces as a hosted product.",
    published: "2026-07-20",
    updated: "2026-10-01",
    seoTitle: "Turnkey AI System vs Building Your Own AI Agent",
    author: "construct-team",
    tags: ["comparison", "agent-frameworks", "diy", "ai-employee"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "construct-vs-gemini-spark",
    title: "Construct vs Gemini Spark",
    description:
      "Construct gives your team an AI employee from $9 a month, with no Google subscription needed. Gemini Spark needs Google AI Pro or Ultra and a personal account.",
    published: "2026-10-25",
    seoTitle: "Gemini Spark Alternative: Construct vs Spark (2026)",
    author: "construct-team",
    tags: ["comparison", "gemini-spark", "google-workspace", "ai-employee"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "construct-vs-genspark-claw",
    title: "Construct vs Genspark Claw",
    description:
      "Construct gives a small team one AI employee for a fixed $9 a month, with no per-message billing. Genspark Claw is a reported $39.99 machine plus credits.",
    published: "2026-10-20",
    seoTitle: "Genspark Claw Alternative: Construct vs Genspark Claw (2026)",
    author: "construct-team",
    tags: ["comparison", "genspark", "ai-employee"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "construct-vs-lindy",
    title: "Construct vs Lindy",
    description:
      "Construct vs Lindy on pricing, where each works, memory, activity records, and model keys. Lindy starts at $29.99 per user; Construct starts at $9.",
    published: "2026-10-07",
    seoTitle: "Lindy Alternative: Construct vs Lindy (2026)",
    author: "construct-team",
    tags: ["comparison", "ai-employee", "small-business"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "construct-vs-manus",
    title: "Construct vs Manus",
    description:
      "Construct vs Manus on price, recurring work, triggers, persistence, and channels. Manus starts free with Pro at $20 in credits; Construct starts at $9.",
    published: "2026-11-18",
    seoTitle: "Manus Alternative: Construct vs Manus (2027)",
    author: "construct-team",
    tags: ["comparison", "ai-agent", "manus"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "construct-vs-muse",
    title: "Construct vs Muse for Small Business",
    description:
      "Construct gives a small team one AI employee, with shared files and schedules, from $9 a month. Muse is one person's agent, in the US and Canada only.",
    published: "2026-10-12",
    seoTitle: "Muse for Small Business vs Construct (2026)",
    author: "construct-team",
    tags: ["comparison", "small-business", "ai-employee"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "construct-vs-openai-dots",
    title: "Construct vs ChatGPT Dots",
    description:
      "Construct gives you an always-on AI employee from $9 a month on the model you choose. ChatGPT Dots needs a $100 to $200 ChatGPT Pro plan. How they compare.",
    published: "2026-10-01",
    seoTitle: "ChatGPT Dots Alternative: Construct vs Dots",
    author: "construct-team",
    tags: ["comparison", "chatgpt", "ai-employee"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "construct-vs-openclaw",
    title: "Construct vs OpenClaw",
    description:
      "Construct is a hosted AI employee for a fixed $9 a month, with no per-message billing. OpenClaw is free software, but you run the server and pay for tokens.",
    published: "2026-10-21",
    seoTitle: "OpenClaw vs Construct: Self-Hosted Agent vs Managed AI Employee",
    author: "construct-team",
    tags: ["comparison", "openclaw", "ai-employee"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "construct-vs-perplexity-computer",
    title: "Construct vs Perplexity Computer",
    description:
      "Construct vs Perplexity Computer on price, credits, research, recurring work, memory, and channels. Perplexity Max is about $200; Construct starts at $9.",
    published: "2026-11-19",
    seoTitle:
      "Perplexity Computer Alternative: Construct vs Perplexity Computer",
    author: "construct-team",
    tags: ["comparison", "ai-agent", "perplexity"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "construct-vs-simular-sai",
    title: "Construct vs Simular Sai",
    description:
      "Construct gives a small team an AI employee with shared files, schedules, and email from $9 a month. See how it compares with Simular Sai on price and apps.",
    published: "2026-11-26",
    seoTitle: "Simular Sai Alternative: Construct vs Sai (2027)",
    author: "construct-team",
    tags: ["comparison", "simular", "ai-agent"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "construct-vs-viktor",
    title: "Construct vs Viktor",
    description:
      "Construct vs Viktor on price, Slack behavior, approvals, memory, and where the work lives. Viktor starts at $50 per workspace; Construct starts at $9.",
    published: "2026-10-28",
    seoTitle: "Viktor Alternative: Construct vs Viktor (2026)",
    author: "construct-team",
    tags: ["comparison", "ai-employee", "viktor"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "construct-vs-zapier",
    title: "Construct vs Zapier, Make, and n8n",
    description:
      "Compare Construct with Zapier, Make, and n8n for deterministic workflows, agentic steps, scheduling, and ambiguous multi-step work.",
    published: "2026-07-20",
    updated: "2026-10-01",
    author: "construct-team",
    tags: ["comparison", "zapier", "make", "n8n", "workflow-automation"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "customer-story-1",
    title: "Customer story: how [customer] handed [job] to an AI employee",
    description:
      "How [customer], a [team size] [industry] team, delegated [job] to Construct: the setup, what changed in [metric], what still needs a person.",
    published: "2026-11-15",
    seoTitle: "[Customer] and Construct: [job] with an AI employee",
    author: "ankush",
    tags: ["ai-employee", "small-business", "workflow-automation"],
    kind: "article",
    draft: true,
  },
  {
    slug: "gemini-spark-alternatives",
    title:
      "Gemini Spark alternatives, including for Workspace accounts and the UK and EU",
    description:
      "Gemini Spark needs a personal Google account and skips the UK and EU. Compare 7 always-on agents on price, work accounts, and regional availability.",
    published: "2026-10-09",
    seoTitle: "Gemini Spark Alternatives (2026): Options for Work Accounts",
    author: "construct-team",
    tags: ["comparison", "gemini-spark", "google-workspace", "ai-employee"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "grokbot-alternative",
    title: "Grok Bot Alternative: Construct vs Grok Bot",
    description:
      "Compare Construct and Grok Bot on monthly pricing, workflows, integrations, memory, and model choice for small teams.",
    published: "2026-09-10",
    updated: "2026-10-01",
    seoTitle: "Grok Bot Alternative: Construct vs Grok Bot",
    author: "construct-team",
    tags: ["comparison", "ai-employee", "workflow-automation"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "hermes-vs-openclaw-vs-managed",
    title: "Hermes Agent vs OpenClaw vs a managed AI employee",
    description:
      "Hermes Agent and OpenClaw are free to self-host; Nous hosts Hermes from $20 a month. Which suits a non-technical founder, and when a managed agent is simpler.",
    published: "2026-11-01",
    seoTitle: "Hermes Agent vs OpenClaw vs a Managed AI Employee (2026)",
    author: "construct-team",
    tags: ["comparison", "openclaw", "hermes-agent", "ai-employee"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "hire-an-ai-employee",
    title: "Hire Your First AI Employee: A 30-Day Plan",
    description:
      "A week-by-week plan for your first AI employee: which jobs to give it first, how to supervise it, and the signals that say expand or stop by day 30.",
    published: "2026-11-17",
    seoTitle: "How to Hire an AI Employee: A Week-by-Week 30-Day Plan",
    author: "nischal",
    tags: ["ai-employee", "ai-agent", "small-business"],
    kind: "guide",
    draft: true,
  },
  {
    slug: "hosted-openclaw-alternatives",
    title: "Hosted OpenClaw alternatives: managed claws vs an AI employee",
    description:
      "OpenClaw has no hosted tier. Compare managed OpenClaw hosts from $5.99 a month, Genspark Claw, hosted Hermes, and AI employees that need no server.",
    published: "2026-10-18",
    seoTitle:
      "Hosted OpenClaw Alternatives: Run It Without Self-Hosting (2026)",
    author: "construct-team",
    tags: ["comparison", "openclaw", "ai-employee", "ai-agent"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "how-to-choose-an-ai-agent-platform-for-your-team",
    title: "How to Choose an AI Agent Platform for Your Team",
    description:
      "A vendor-agnostic evaluation checklist for AI agent platforms: pilot-failure data, six evaluation criteria, governance pressure, and a scorecard you can reuse.",
    published: "2026-07-28",
    updated: "2026-10-01",
    author: "nischal",
    tags: ["ai-agent", "ai-employee", "governance", "product"],
    kind: "guide",
    draft: false,
  },
  {
    slug: "is-construct-computer-safe",
    title:
      "Is Construct Computer safe? Data, permissions and what the agent can touch",
    description:
      "What Construct stores, who processes it, what its AI agent can reach, the controls that limit it, and the risks that remain. Written by the team that builds it.",
    published: "2026-11-30",
    seoTitle: "Is Construct Computer Safe? Data, Permissions and Risks (2027)",
    author: "ankush",
    tags: ["governance", "product", "ai-employee"],
    kind: "article",
    draft: true,
  },
  {
    slug: "jev-ai-agents",
    title: "We put Jev inside our AI employee",
    description:
      "We shipped TypeSafe's Jev into our AI employee's memory five days after launch: measured latency, how we set a 0.7 threshold, where Jev fails, and what it costs.",
    published: "2026-09-30",
    seoTitle: "Jev for AI Agents: What We Learned Running It in Production",
    author: "ankush",
    tags: ["ai-agent", "jev", "reliability", "decision-models"],
    kind: "article",
    draft: false,
  },
  {
    slug: "lindy-alternatives",
    title: "Lindy alternatives, compared honestly",
    description:
      "Lindy costs $29.99 per user a month. Compare 10 alternatives on price, billing unit, and where they work, with an honest pick for each use case.",
    published: "2026-10-10",
    seoTitle: "Lindy Alternatives (2026): 10 Options Compared Honestly",
    author: "construct-team",
    tags: ["comparison", "ai-employee", "small-business"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "manus-alternatives",
    title: "Manus alternatives for recurring business work",
    description:
      "Construct runs recurring business work from $9 a month and keeps every file between runs. Manus bills credits per run. 8 Manus alternatives compared.",
    published: "2026-11-09",
    seoTitle: "Manus Alternatives for Recurring Workflows (2027)",
    author: "construct-team",
    tags: ["comparison", "ai-agent", "workflow-automation", "manus"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "muse-for-small-business-alternatives",
    title: "Muse for Small Business alternatives: 9 AI agents for work",
    description:
      "Compare 9 Muse for Small Business alternatives, led by Construct at $9 a month, with prices checked October 1, 2026, and where each one fits.",
    published: "2026-10-06",
    seoTitle: "Meta Muse for Small Business Alternatives (2026)",
    author: "construct-team",
    tags: ["comparison", "ai-employee", "small-business"],
    kind: "comparison",
    draft: false,
  },
  {
    slug: "perplexity-computer-alternatives",
    title: "Perplexity Computer alternatives under $200 a month",
    description:
      "Perplexity Max costs about $200 a month. Construct runs recurring cloud work from $9 on a plan with published limits. 8 cheaper alternatives compared.",
    published: "2026-11-05",
    seoTitle: "Perplexity Computer Alternatives Under $200 a Month (2026)",
    author: "construct-team",
    tags: ["comparison", "ai-agent", "pricing", "perplexity"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "perplexity-computer-vs-cowork-vs-manus",
    title: "Perplexity Computer vs Claude Cowork vs Manus for background work",
    description:
      "Which agent keeps working with your laptop closed? Perplexity Computer ($200 Max), Claude Cowork ($20 Pro), and Manus (free to start) compared for background work.",
    published: "2026-11-06",
    seoTitle: "Perplexity Computer vs Claude Cowork vs Manus (2026)",
    author: "construct-team",
    tags: ["comparison", "ai-agent", "scheduling"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "running-ai-agents-on-cloudflare-not-vms",
    title: "All our Agents get computers, we pay for almost none",
    description:
      "Construct is an AI employee with a real Linux computer per user. Don't get excited - we are not paying for all of them. How we run that on Cloudflare Durable Objects, Sandboxes, and R2.",
    published: "2026-07-31",
    seoTitle: "Running AI Agents on Cloudflare Without Always-On VMs",
    author: "ankush",
    tags: ["engineering", "cloudflare", "durable-objects", "infrastructure"],
    kind: "article",
    draft: false,
  },
  {
    slug: "sintra-alternatives",
    title: "Sintra alternatives that actually do the work",
    description:
      "Sintra X lists at $97 a month with 250 credits, and its FAQ says every helper runs as a chatbot. 8 alternatives that act in your tools, compared.",
    published: "2026-11-13",
    seoTitle: "Sintra AI Alternatives That Actually Do Tasks (2027)",
    author: "construct-team",
    tags: ["comparison", "ai-employee", "small-business"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "sintra-vs-marblism-vs-lindy",
    title: "Sintra vs Marblism vs Lindy for a small business",
    description:
      "Sintra is $97 a month list, Marblism $44, Lindy $29.99 per user. Compare what each does, how each is metered, and which fits your small business.",
    published: "2026-11-14",
    seoTitle: "Sintra vs Marblism vs Lindy (2027): Which AI Staff Fits?",
    author: "construct-team",
    tags: ["comparison", "ai-employee", "small-business"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "viktor-alternatives",
    title: "Viktor alternatives: AI employees that live in Slack",
    description:
      "Viktor starts at $50 a month per workspace. Compare 7 Slack AI employees on price, billing unit, approvals, and where the work runs, from $9 a month.",
    published: "2026-10-27",
    seoTitle: "Viktor Alternatives: 7 AI Employees That Live in Slack (2026)",
    author: "construct-team",
    tags: ["comparison", "ai-employee", "viktor"],
    kind: "comparison",
    draft: true,
  },
  {
    slug: "what-is-an-ai-employee",
    title: "What is an AI employee?",
    description:
      "Learn what an AI employee is, how it differs from a chatbot, and how Construct completes work across email, Slack, browser, and connected apps.",
    published: "2026-07-02",
    updated: "2026-10-01",
    seoTitle: "What Is an AI Employee? Definition and Examples",
    author: "ankush",
    tags: ["ai-agent", "product", "ai-employee"],
    kind: "article",
    draft: false,
  },
  {
    slug: "where-ai-agents-fail",
    title: "Where AI agents fail: what real runs show",
    description:
      "Where AI agents fail in real business runs: at which step, on which tool, and how often a resumable run recovers. Our method, definitions and data.",
    published: "2026-11-10",
    seoTitle: "Why AI Agents Fail: An Analysis of Real Agent Runs",
    author: "ankush",
    tags: ["ai-agent", "reliability", "engineering"],
    kind: "article",
    draft: true,
  },
  {
    slug: "zen-mode",
    title: "Zen Mode: some days you just want it done",
    description:
      "Zen Mode is a chat-first way into Construct's AI computer. Ask once, it works in the background, asks when it needs you, and runs on your phone.",
    published: "2026-10-04",
    seoTitle: "Construct Zen Mode: Chat-First AI Agent With Its Own Computer",
    author: "nischal",
    tags: ["product", "ai-agent", "ai-employee", "zen-mode"],
    kind: "guide",
    draft: false,
  },
];
