import { existsSync } from "node:fs";
import { appendFile, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import sharp from "sharp";

import { generateImage } from "./og/gemini.mjs";
import {
  posterDirectory,
  readSources,
  styleDirectory,
} from "./og/manifest.mjs";
import {
  POSTER_ASPECT,
  buildPosterPrompt,
  posterReferences,
  stylePlatePath,
} from "./og/poster.mjs";
import {
  defaultModel,
  formatTokens,
  formatUsd,
  ratesFor,
} from "./og/pricing.mjs";
import { loadCards } from "./og/routes.mjs";

/**
 * Renders the social cards through Gemini.
 *
 * Only ever writes into `assets/og/`; cropping and publishing stay in
 * `pnpm og`, so a bad generation can be deleted and retried without
 * `public/og/` ever having held it. Existing cards are never overwritten
 * without `--force`, because the whole point of committing sources is that a
 * good card stays good.
 *
 *   pnpm og:master <name>               make the style plate every card copies
 *   pnpm og:generate                    fill in every missing card
 *   pnpm og:generate --only <name>      just one
 *   pnpm og:generate --force <name>     replace one that already exists
 *   pnpm og:generate --candidates 3     write 3 options to choose between
 *   pnpm og:generate --dry-run          show what would be spent, call nothing
 *   pnpm og:pick <name> <n>             promote a candidate to the real file
 *
 * The style plate comes first and is the whole consistency story: it is
 * attached to every later call as the layout and typography to copy. Regenerate
 * it and the set no longer matches itself, so it is generated by an explicit
 * command rather than falling out of a normal run.
 */

const root = process.cwd();
const candidateDirectory = path.join(posterDirectory, "candidates");
const ledgerPath = path.join(root, "assets/og/generation-log.jsonl");

// .env is gitignored; this is the only place the key is read from.
try {
  process.loadEnvFile(path.join(root, ".env"));
} catch {
  // No .env — the key may come from the environment instead.
}

const model = process.env.GEMINI_IMAGE_MODEL ?? defaultModel;
const imageSize = process.env.GEMINI_IMAGE_SIZE ?? "2K";

function destinationFor(card) {
  return path.join(posterDirectory, `${card.name}.webp`);
}

/**
 * True when there is already a card that would make this generation pointless.
 * A hand-made image in `assets/og/` wins outright at publish time, so nothing
 * is generated under one.
 */
async function alreadyDone(card) {
  const { custom } = await readSources(card.name, card.stem);
  return Boolean(custom) || existsSync(destinationFor(card));
}

/** One line per generation, so lifetime spend survives across runs. */
async function recordSpend(entry) {
  await appendFile(ledgerPath, `${JSON.stringify(entry)}\n`);
}

async function lifetimeSpend() {
  try {
    const lines = (await readFile(ledgerPath, "utf8")).trim().split("\n");
    return lines
      .filter(Boolean)
      .reduce((total, line) => total + (JSON.parse(line).usd ?? 0), 0);
  } catch {
    return 0;
  }
}

/**
 * The model returns PNG. WebP q95 stores it several times smaller and the
 * published JPEG comes out within a few KB of identical.
 */
async function writeCard(destination, data) {
  await mkdir(path.dirname(destination), { recursive: true });
  await writeFile(
    destination,
    await sharp(data).webp({ quality: 95, effort: 6 }).toBuffer(),
  );
}

async function generateOne(card, { label, references, note }) {
  const started = Date.now();
  const result = await generateImage({
    model,
    prompt: buildPosterPrompt({ ...card, note }),
    references,
    aspectRatio: POSTER_ASPECT,
    imageSize,
  });
  const seconds = ((Date.now() - started) / 1000).toFixed(1);
  console.log(
    `${formatUsd(result.cost.usd)}  ` +
      `(${formatTokens(result.cost.input)} in / ${formatTokens(result.cost.output)} out, ${seconds}s)`,
  );
  await recordSpend({
    at: new Date().toISOString(),
    name: label,
    layout: "poster",
    model,
    imageSize,
    input: result.cost.input,
    output: result.cost.output,
    usd: result.cost.usd,
  });
  return result;
}

const args = process.argv.slice(2);
function flag(name) {
  const index = args.indexOf(name);
  return index === -1 ? null : (args[index + 1] ?? "");
}

function select(cards, name) {
  const card = cards.find((entry) => entry.name === name);
  if (!card) {
    throw new Error(
      `Unknown OG name "${name}". Known names:\n  ${cards.map((entry) => entry.name).join("\n  ")}`,
    );
  }
  return card;
}

const cards = await loadCards();

// ─── The style plate ─────────────────────────────────────────────────────────

/**
 * Generated without a plate attached, because there is not one yet: this call
 * is the only one in the set working from the written contract alone, which is
 * why it is worth generating several and looking hard at the result before
 * committing one. Everything after it copies whatever lands here, mistakes
 * included.
 */
if (args[0] === "--master") {
  const card = select(cards, args[1] ?? "home");
  const count = Number(flag("--candidates") ?? 1);
  await mkdir(styleDirectory, { recursive: true });

  for (let candidate = 1; candidate <= count; candidate += 1) {
    const label = count > 1 ? `master-${candidate}` : "master";
    process.stdout.write(`[${candidate}/${count}] ${label} … `);
    const result = await generateOne(card, {
      label,
      references: posterReferences().filter(
        (reference) => !reference.file.includes("style/master"),
      ),
      note: "This card is the style plate for the whole set. Render the typography with particular care: it is what every other card will be told to copy.",
    });
    await writeCard(path.join(styleDirectory, `${label}.webp`), result.data);
    console.log(
      `        ${path.relative(root, path.join(styleDirectory, `${label}.webp`))}`,
    );
  }

  console.log(
    count > 1
      ? `\nLook at all ${count}, then promote one:\n  cp assets/og/style/master-<n>.webp assets/og/style/master.webp`
      : `\nEvery later generation now copies this card. Check it closely before generating the set.`,
  );
  process.exit(0);
}

// `pnpm og:pick <name> <n>` — promote a candidate and drop the rest.
if (args[0] === "--pick") {
  const card = select(cards, args[1]);
  const chosen = path.join(candidateDirectory, `${card.name}-${args[2]}.webp`);
  const destination = destinationFor(card);
  await mkdir(path.dirname(destination), { recursive: true });
  await writeFile(destination, await readFile(chosen));
  console.log(
    `${path.relative(root, chosen)} → ${path.relative(root, destination)}\nRun \`pnpm og\` to publish it.`,
  );
  process.exit(0);
}

// ─── The set ─────────────────────────────────────────────────────────────────

const forced = flag("--force");
const only = flag("--only");
const candidates = Number(flag("--candidates") ?? 1);
const dryRun = args.includes("--dry-run");

let queue = cards;
if (forced !== null) queue = [select(cards, forced)];
else if (only !== null) queue = [select(cards, only)];

const missing = [];
for (const card of queue) {
  // `--force` is the only way past a card that already exists.
  if (forced === null && (await alreadyDone(card))) continue;
  missing.push(card);
}

const skipped = queue.length - missing.length;
const calls = missing.length * candidates;
const rates = ratesFor(model);

if (!existsSync(stylePlatePath)) {
  throw new Error(
    `No style plate at ${path.relative(root, stylePlatePath)}.\n` +
      `The set is held together by every card copying one approved card, so make that one first:\n` +
      `  pnpm og:master home --candidates 3`,
  );
}

console.log(
  `Model ${model} at ${imageSize} (in ${formatUsd(rates.input)}/1M, out ${formatUsd(rates.output)}/1M)`,
);
console.log(
  `${missing.length} to generate, ${skipped} already done, ${calls} call(s) at ${candidates} candidate(s) each.\n`,
);

if (!missing.length) {
  console.log(
    "Nothing to do. Use `--force <name>` to replace an existing card.",
  );
  process.exit(0);
}
if (dryRun) {
  for (const card of missing) console.log(`  would generate ${card.name}`);
  console.log(
    `\nDry run — nothing called. Roughly ${formatUsd(calls * 0.18)} at current Pro rates.`,
  );
  process.exit(0);
}

let spent = 0;
let generated = 0;
const failures = [];
let index = 0;

for (const card of missing) {
  for (let candidate = 1; candidate <= candidates; candidate += 1) {
    index += 1;
    const label = candidates > 1 ? `${card.name} #${candidate}` : card.name;
    process.stdout.write(`[${index}/${calls}] ${label} … `);
    try {
      const result = await generateOne(card, {
        label,
        references: posterReferences(),
      });
      await writeCard(
        candidates > 1
          ? path.join(candidateDirectory, `${card.name}-${candidate}.webp`)
          : destinationFor(card),
        result.data,
      );
      spent += result.cost.usd;
      generated += 1;
      console.log(`        running total ${formatUsd(spent)}`);
    } catch (error) {
      failures.push({ name: card.name, message: error.message });
      console.log(`FAILED — ${error.message}`);
    }
  }
}

const lifetime = await lifetimeSpend();
console.log(`\n${"─".repeat(52)}`);
console.log(`Generated   ${generated}/${calls}`);
console.log(`This run    ${formatUsd(spent)}`);
console.log(
  `Lifetime    ${formatUsd(lifetime)}  (${path.relative(root, ledgerPath)})`,
);

if (failures.length) {
  console.log(`\nFailed (${failures.length}):`);
  for (const failure of failures) {
    console.log(`  ${failure.name}: ${failure.message}`);
  }
}
if (candidates > 1) {
  console.log(
    `\nCandidates are in ${path.relative(root, candidateDirectory)}/.\n` +
      `Promote one with \`pnpm og:pick <name> <n>\`.`,
  );
} else if (generated) {
  console.log(`\nRun \`pnpm og\` to publish the new cards into public/og/.`);
}
process.exitCode = failures.length ? 1 : 0;
